# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
from io import BytesIO

import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import sys
import pandas as pd
import matplotlib.pyplot as plt
from PyQt5.QtWidgets import QApplication, QMainWindow, QGraphicsScene, QGraphicsView, QVBoxLayout, QWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1315, 802)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 3)
        self.horizontalLayout_4.setStretch(4, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_2.addWidget(self.graphicsView_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_3.addWidget(self.graphicsView_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.verticalLayout_4.addWidget(self.graphicsView_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_5.addWidget(self.graphicsView_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout_6.addWidget(self.graphicsView_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.verticalLayout_7.addWidget(self.graphicsView_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.verticalLayout_8.addWidget(self.graphicsView_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1315, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.on_load()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "设备选择"))
        self.pushButton.setText(_translate("MainWindow", "打开设备"))
        self.pushButton_2.setText(_translate("MainWindow", "设备配置"))
        self.groupBox.setTitle(_translate("MainWindow", "实时监控"))
        self.label_2.setText(_translate("MainWindow", "测点1"))
        self.label_3.setText(_translate("MainWindow", "测点2"))
        self.label_4.setText(_translate("MainWindow", "测点3"))
        self.label_5.setText(_translate("MainWindow", "测点4"))
        self.label_6.setText(_translate("MainWindow", "测点5"))
        self.label_7.setText(_translate("MainWindow", "测点6"))
        self.label_8.setText(_translate("MainWindow", "测点7"))
        self.label_9.setText(_translate("MainWindow", "测点8"))
        self.label_10.setText(_translate("MainWindow", "设备表格"))

    def on_load(self):
        self.load_image_to_view(self.graphicsView)
        self.load_image_to_view(self.graphicsView_2)
        self.load_image_to_view(self.graphicsView_3)
        self.load_image_to_view(self.graphicsView_4)
        self.load_image_to_view(self.graphicsView_5)
        self.load_image_to_view(self.graphicsView_6)
        self.load_image_to_view(self.graphicsView_7)
        self.load_image_to_view(self.graphicsView_8)

    def load_image_to_view(self, graphicsView):
        # 创建一个 matplotlib 图像
        fig, ax = plt.subplots(figsize=(4.5, 2.5))  # 增加图像的大小
        ax.plot(np.random.rand(10))  # 示例图像（随机数据的折线图）
        ax.set_title("Sample Plot")

        # 保存图像到内存
        buf = BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)  # Rewind the buffer to the beginning

        # 从内存加载图像并转换为 QPixmap
        pixmap = QtGui.QPixmap()
        pixmap.loadFromData(buf.getvalue())  # 使用图像数据加载 QPixmap

        # 设置图像到 QGraphicsView
        scene = QGraphicsScene()
        scene.addPixmap(pixmap)

        # 设置 QGraphicsView 的 scene
        graphicsView.setScene(scene)

        # # 设置 QGraphicsView 自适应大小并移除滚动条
        # graphicsView.setRenderHint(QtGui.QPainter.Antialiasing)  # 可选，改进渲染效果
        # graphicsView.setRenderHint(QtGui.QPainter.SmoothPixmapTransform)  # 平滑变换
        # graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)  # 禁用水平滚动条
        # graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)  # 禁用垂直滚动条
        #
        # # 自适应图像大小
        # graphicsView.setAlignment(QtCore.Qt.AlignCenter)  # 图像居中
        # graphicsView.fitInView(scene.sceneRect(), QtCore.Qt.KeepAspectRatio)  # 自适应大小，保持纵横比

        # 调整图像填满视图
        # graphicsView.setRenderHint(QtGui.QPainter.SmoothPixmapTransform)
        # graphicsView.fitInView(scene.sceneRect(), QtCore.Qt.IgnoreAspectRatio)  # 让图像填满视图

        # 关闭 matplotlib 图像以释放资源
        plt.close(fig)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
